---
#### Sonoffs ####

## SONOFF BASIC 1 ##
- platform: mqtt
  name: "Sonoff1"
  command_topic: "cmnd/sonoff1/power"
  state_topic: "stat/sonoff1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  #retain: true
  
## SONOFF BASIC 2 ##
- platform: mqtt
  name: "Sonoff2"
  command_topic: "cmnd/sonoff2/power"
  state_topic: "stat/sonoff2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  #retain: true
  
## SONOFF POW 1 ##
- platform: mqtt
  name: "SonoffPOW1"
  command_topic: "sonoffPOW1/cmnd/power"
  state_topic: "sonoffPOW1/stat/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  #retain: true  

## SONOFF POW 2 ##
- platform: mqtt
  name: "SonoffPOW2"
  command_topic: "sonoffPOW2/cmnd/power"
  state_topic: "sonoffPOW2/stat/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  #retain: true