---
#### Template switches ####

- platform: template
  switches:
  
    ## VACUUM TOGGLE ##
    vacuum:
      friendly_name: Vacuum
      value_template: "{{ is_state('vacuum.Vacuum', 'cleaning') }}"
      turn_on:
        entity_id: vacuum.Vacuum
        service: vacuum.start
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.Vacuum
    
    ## VACUUM WEEKDAYS ##
    vacuum_weekdays:
      friendly_name: Støvug ukedager
      value_template: "{{ is_state('automation.vacuum_weekdays', 'on') }}"
      turn_on:
        service: automation.turn_on
        entity_id: automation.vacuum_weekdays
      turn_off:
        service: automation.turn_off
        entity_id: automation.vacuum_weekdays

    ## READING LAMP ##
    reading_lamp:
      friendly_name: Leselampe
      value_template: "{{ is_state_attr('light.reading_lamp', 'brightness', 254) and is_state_attr('light.reading_lamp', 'rgb_color', (255,205,166))}}"
      turn_on:
        entity_id: light.reading_lamp
        service: light.turn_on
        data:
          color_temp: '250'
          brightness_pct: '100'
      turn_off:
        service: light.turn_on
        data_template:
          entity_id: light.reading_lamp
          brightness: "{{state_attr('light.couch', 'brightness') | int}}"
          color_temp: "{{state_attr('light.couch', 'color_temp') | int}}"