- id: 1c985a4a2e34434db7189ebc636ef346
  alias: VW CarID Climatisation on
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_climatisation
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Klimaanlegg er på
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 0bf3b9b711a54d7ea001482a7e635d03
  alias: VW CarID Climatisation off
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_climatisation
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Klimaanlegg er av
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 9336a921fb0543c1b347c460092f9c8e
  alias: VW CarID Charging
  trigger:
  - entity_id: switch.vw_carid_charging
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Batteriet lades
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 8ffa860b40474b288aafc9e9fee4ce21
  alias: VW CarID Battery fully charged
  trigger:
  - above: '99'
    entity_id: sensor.wvwzzzauzfw911702_battery_level
    platform: numeric_state
  action:
  - data:
      message: Batteriet er 100%
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: '1540576707188'
  alias: Vacuum weekdays
  trigger:
  - at: '11:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: template
    value_template: '{{ states("device_tracker.simonsiniphone7_2") != "home" }}'
  action:
  - data:
      entity_id: switch.vacuum
    service: switch.turn_on
- id: '1540900686576'
  alias: VW Charging stopped
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_charging
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Lading avbrutt
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: '1541457544610'
  alias: tv off when lights off
  trigger:
  - entity_id: light.livingroom_lights
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '21:30'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: remote.harmony_hub
    service: remote.turn_off
- id: d7fd9c9686bb4e56a2fe5e8268cc1b58
  alias: dim lights at sundown
  trigger:
  - event: sunset
    offset: 00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'on'
  action:
  - data:
      brightness: '45'
      color_temp: '450'
      entity_id: light.livingroom_lights
      transition: '900'
    service: light.turn_on
- id: '1542311037089'
  alias: Tv off at night
  trigger:
  - at: 03:00
    platform: time
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'off'
  action:
  - service: script.turnofftv
- id: '1543413624056'
  alias: Heater on before bed
  trigger:
  - at: '20:30'
    platform: time
  condition:
  - above: '-1000'
    below: '15'
    condition: numeric_state
    entity_id: sensor.weather_temperature
  - condition: state
    entity_id: device_tracker.simonsiniphone7_2
    state: home
  action:
  - data:
      entity_id: switch.tradfri_control_outlet
    service: switch.turn_on
- id: '1543414096425'
  alias: Heater off in the morning
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.tradfri_control_outlet
    service: switch.turn_off
- id: '1549906953663'
  alias: Radiolights on
  trigger:
  - entity_id: light.livingroom_lights
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.sonoff2
    service: switch.turn_on
  - data:
      entity_id: switch.sonoff1
    service: switch.turn_on
- id: '1549907033692'
  alias: Radiolights off
  trigger:
  - entity_id: light.livingroom_lights
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.sonoff2
    service: switch.turn_off
  - data:
      entity_id: switch.sonoff1
    service: switch.turn_off
- id: '1552136838463'
  alias: Lys holder seg på
  trigger:
  - entity_id: light.kommode
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - delay: '2'
  - data:
      entity_id: light.spotter_stue
    service: light.turn_on
  - delay: '30'
  - data:
      entity_id: light.spotter_stue
    service: light.turn_off
- id: '1552140807307'
  alias: Alarm 0800
  trigger:
  - at: 06:50:00
    platform: time
  condition:
  - condition: state
    entity_id: input_select.alarm
    state: 08:00
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: media_player.soverom
      volume_level: '0.10'
    service: media_player.volume_set
  - data:
      entity_id: media_player.bathroom
      volume_level: '0.13'
    service: media_player.volume_set
  - data:
      entity_id: media_player.kitchen
      volume_level: '0.13'
    service: media_player.volume_set
  - data:
      entity_id: media_player.soverom
      source: NRK P3
    service: media_player.select_source
  - data:
      entity_id: media_player.bathroom
      source: NRK P3
    service: media_player.select_source
  - data:
      brightness_pct: '80'
      entity_id: light.bedroom_lights
      transition: '300'
    service: light.turn_on
  - delay: '2400'
  - data:
      entity_id: media_player.soverom
    service: media_player.media_pause
  - data:
      entity_id: media_player.bathroom
    service: media_player.media_pause
- id: '1552140807307'
  alias: Alarm 0900
  trigger:
  - at: 07:50:00
    platform: time
  condition:
  - condition: state
    entity_id: input_select.alarm
    state: 09:00
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: media_player.soverom
      volume_level: '0.10'
    service: media_player.volume_set
  - data:
      entity_id: media_player.bathroom
      volume_level: '0.13'
    service: media_player.volume_set
  - data:
      entity_id: media_player.kitchen
      volume_level: '0.13'
    service: media_player.volume_set
  - data:
      entity_id: media_player.soverom
      source: NRK P3
    service: media_player.select_source
  - data:
      entity_id: media_player.bathroom
      source: NRK P3
    service: media_player.select_source
  - data:
      entity_id: light.bedroom_lights
      brightness_pct: '80'
      transition: '300'
    service: light.turn_on
  - delay: 2400
  - data:
      entity_id: media_player.soverom
    service: media_player.media_pause
  - data:
      entity_id: media_player.bathroom
    service: media_player.media_pause
- id: vacuum_empty_routine
  alias: Tøm hver torsdag
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - thu
  - condition: state
    entity_id: switch.vacuum_weekdays
    state: 'on'
  action:
  - entity_id: script.empty_vacuum
    service: script.turn_on
- id: '1553462495588'
  alias: Test
  trigger:
    platform: template
    value_template: '{% if states(''sensor.time'') == (states(''sensor.alarm_clock_time''))
      %}true{% endif %}'
  action:
    service: light.turn_off
    entity_id: light.reading_lamp
- id: '1553555466254'
  alias: Heater off
  trigger:
  - entity_id: light.livingroom_lights
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.sonoffpow2
    service: switch.turn_off
- id: '1553555834085'
  alias: Heater on
  trigger:
  - entity_id: light.livingroom_lights
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.sonoffpow2
    service: switch.turn_on
- id: '1553868410276'
  alias: Vaskemaskin
  trigger:
  - entity_id: binary_sensor.washing_machine
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Vaskemaskinen er ferdig, vennligst tøm den
      title: Vaskemaskin
    service: notify.ios_simon_sin_iphone_7
  - data:
      entity_id: media_player.kitchen
      volume_level: '0.30'
    service: media_player.volume_set
  - data:
      entity_id: media_player.kitchen
      message: '''Vaskemaskinen er ferdig, vennligst tøm den'
    service: tts.google_say
- id: '1235729'
  alias: Holiday Input Effect
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_select.holiday_led_effect
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/mqttstrip/seteffect
      payload: '{{ trigger.to_state.state | string }}'
- alias: Animation Speed
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_number.animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/mqttstrip/setanimationspeed
      payload: '{{ trigger.to_state.state | int }}'
  id: 0fd14437ab554a1aa0e1c76247807749


- id: '1556301453307'
  alias: Alarm automatic
  trigger:
  - entity_id: binary_sensor.pir_entry
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_home
  action:
  - data:
      entity_id: media_player.kitchen, media_player.bathroom, media_player.soverom
      volume_level: 0.7
    service: media_player.volume_set
  - data:
      message: Alarmen er utløst
      title: ALARM
      data:
        push:
          category: "alarm_triggered"
  - data:
      entity_id: media_player.kitchen
      source: Alarm
    service: media_player.select_source
  - data:
      entity_id: input_select.holiday_led_effect
      option: Police All
    service: input_select.select_option

- id: '81293879176'
  alias: Alarm phone notify
  initial_state: true
  trigger:
  - entity_id: binary_sensor.pir_entry
    from: 'off'
    platform: state
    to: 'on'
  action:
    - data:
        message: Alarmen er utløst
        title: ALARM
        data:
          push:
            category: "alarm_triggered"
      service: notify.ios_simon_sin_iphone_7

- id: '891237491'
  alias: Alarm phone
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_home
  action:
  - data:
      entity_id: media_player.kitchen, media_player.bathroom, media_player.soverom
      volume_level: 0.7
    service: media_player.volume_set
  - data:
      message: Alarmen er utløst
      title: ALARM
      data:
        push:
          category: "alarm_triggered"
    service: notify.ios_simon_sin_iphone_7
  - data:
      entity_id: media_player.kitchen
      source: Alarm
    service: media_player.select_source
  - data:
      entity_id: input_select.holiday_led_effect
      option: Police All
    service: input_select.select_option

- id: '817937499029'
  alias: Turn off alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: STOP_ALARM
  action:
  - service: script.turn_off_alarm