#### CONFIGURATION ####

# Welcome to my configuration file. Most of my config is placed in folders
# and is organized by components. A list of all components used is found 
# under. the basic config of Home Assistant.

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml


config: # Enables configuration UI
updater: # Optional, allows Home Assistant developers to focus on popular components.
discovery: # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # Track the sun
system_health:


### COMPONENTS USED ###

# THEMES
frontend: 
  themes: !include_dir_merge_named themes

# IOS ACTIONABLE NOTIFICATIONS
ios: !include components/ios.yaml

# ZONES
zone: !include components/zones.yaml

# LOVELACE
lovelace:
  mode: yaml

# TEXT TO SPEECH
tts: !include components/tts.yaml
   
# CLOUD
cloud: !include components/cloud.yaml

# XIAOMI-VACUUM
vacuum: !include components/vacuum.yaml
 
# Iframe panel
panel_iframe: !include components/panel_iframe.yaml

# TRACKING
#device_tracker: !include components/device_tracker.yaml
# ASUSWRT ROUTER
asuswrt: !include components/asuswrt.yaml
person: !include components/persons.yaml

# HOMEKIT    
homekit: !include components/homekit.yaml
   
# VW CAR
volkswagencarnet: !include components/volkswagen_carnet.yaml

# PLANT MONITORING
plant: !include components/plant.yaml
  
# INFLUXDB
# influxdb: !include components/influxdb.yaml
  
# ALARM PANEL
alarm_control_panel: !include components/alarm_control_panel.yaml

# CAMERAS
camera: !include components/cameras.yaml

# Custom updater
custom_updater: !include components/custom_updater.yaml

# Climate/Thermostat
climate: !include components/climate.yaml

### BASIC INCLUDES ###
# LIGHTS
light: !include components/lights.yaml
# GROUPS
group: !include groups.yaml
# AUTOMATIONS
automation: !include_dir_merge_list automations
# SCRIPTS
script: !include_dir_merge_named scripts
# SENSORS
sensor: !include_dir_merge_list sensors
# BINARY SENSOR    
binary_sensor: !include_dir_merge_list binary_sensors
# SWITCHES
switch: !include_dir_merge_list switches
# INPUT SELECT  
input_select: !include_dir_merge_named input_select
# INPUT NUMBER    
input_number: !include_dir_merge_named input_number
# INPUT BOOLEAN
input_boolean: !include_dir_merge_named input_boolean