---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Hjem
resources: !include_dir_list lovelace/resources/
    
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/livingroom.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/map.yaml
  - !include lovelace/views/test.yaml
