---
#### LIGHTS ####

# LIVINGROOM SPOTS
- platform: group
  name: Spotter Stue
  entities:
    - light.livingroom_spot_1
    - light.livingroom_spot_2
    - light.livingroom_spot_3

# LIVINGROOM LIGHTS
- platform: group
  name: Livingroom Lights
  entities:
    - light.reading_lamp
    - light.kommode
    - light.couch
    - light.spotter_stue
    - light.dining_room

# BEDROOM LIGHTS
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_spot_1
    - light.bedroom_spot_2
    - light.bedroom_spot_3
 
# TORAS LIGHTS
- platform: group
  name: Toras Lights
  entities:
    - light.bedroom_tora
    
# ALL LIGHTS
- platform: group
  name: All Lights
  entities:
    - light.livingroom_lights
    - light.bedroom_lights
    - light.toras_lights


# OUTDOOR LIGHTS
- platform: mqtt
  name: "Holiday Lights"
  command_topic: "bruh/mqttstrip/setpower"
  state_topic: "bruh/mqttstrip/setpowerpub"
  rgb_state_topic: "bruh/mqttstrip/setcolorpub"
  rgb_command_topic: "bruh/mqttstrip/setcolor"
  brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
  brightness_command_topic: "bruh/mqttstrip/setbrightness"
  optimistic: false
  

- platform: mqtt 
  schema: json
  name: "PinkyLEDs"
  command_topic: "cmnd/PinkyLEDs"
  state_topic: "stat/PinkyLEDs"
  availability_topic: "LWT/PinkyLEDs"
  payload_available:  "Online"
  payload_not_available: "Offline"
  white_value: true
  optimistic: false
  rgb: true
  flash_time_short: 1
  flash_time_long: 5
  brightness: true
  effect: true
  effect_list:
    - "Confetti"
    - "Glitter"
    - "Juggle"
    - "Sinelon"
    - "Solid"
    - "Christmas"
    - "Candy Cane"
    - "Holly Jolly"
    - "Valentine"
    - "Lovey Day"
    - "St Patty"
    - "Easter"
    - "USA"
    - "Independence"
    - "Go Blue"
    - "Hail"
    - "Touchdown"
    - "Halloween"
    - "Punkin"
    - "Thanksgiving"
    - "Turkey Day"
    - "BPM"
    - "Cyclon Rainbow"
    - "Dots"
    - "Fire"
    - "Lightning"
    - "Police All"
    - "Police One"
    - "Rainbow"
    - "Glitter Rainbow"
    - "Ripple"
    - "Twinkle"
    - "E131"

- platform: mqtt 
  schema: json
  name: "PinkyLED2"
  command_topic: "cmnd/PinkyLED2"
  state_topic: "stat/PinkyLED2"
  availability_topic: "LWT/PinkyLED2"
  payload_available:  "Online"
  payload_not_available: "Offline"
  white_value: true
  optimistic: false
  rgb: true
  flash_time_short: 1
  flash_time_long: 5
  brightness: true
  effect: true
  effect_list:
    - "Confetti"
    - "Glitter"
    - "Juggle"
    - "Sinelon"
    - "Solid"
    - "Christmas"
    - "Candy Cane"
    - "Holly Jolly"
    - "Valentine"
    - "Lovey Day"
    - "St Patty"
    - "Easter"
    - "USA"
    - "Independence"
    - "Go Blue"
    - "Hail"
    - "Touchdown"
    - "Halloween"
    - "Punkin"
    - "Thanksgiving"
    - "Turkey Day"
    - "BPM"
    - "Cyclon Rainbow"
    - "Dots"
    - "Fire"
    - "Lightning"
    - "Police All"
    - "Police One"
    - "Rainbow"
    - "Glitter Rainbow"
    - "Ripple"
    - "Twinkle"
    - "E131"