---
#### Template binary sensors ####
- platform: template
  sensors:
  
    ## Washing machine sensor ##
    washing_machine:
      friendly_name: "Vaskemaskin"
      delay_off:
        minutes: 2
      value_template: >-
        {{ states('sensor.pow1_power')|float > 1 }}
    
    ## Motion sensor entry ##
    pir_entry:
      friendly_name: "PIR nede"
      device_class: motion
      value_template: "{{ is_state('light.entry', 'on') }}"