esphome:
  name: extra
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
      
light:
  - platform: neopixelbus
    pin: GPIO3
    num_leds: 12
    variant: WS2812
    method: ESP8266_DMA
    name: "NeoPixel Light"
    
#binary_sensor:
#  - platform: gpio
#    pin: GPIO14
#    name: "PIR Sensor"
#    device_class: motion