esphome:
  name: soverom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: D7
    model: DHT22
    temperature:
      name: "Bedroom temperature"
    humidity:
      name: "Bedroom humidity"
    update_interval: 60s