esphome:
  name: stue
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret ssid
  password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:6A:5C:B1
    temperature:
      name: "Xiaomi MiFlora Temperature"
    moisture:
      name: "Xiaomi MiFlora Moisture"
    illuminance:
      name: "Xiaomi MiFlora Illuminance"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora Battery Level"
  - platform: dht
    pin: 2
    model: DHT22
    temperature:
      name: "Livingroom temperature"
    humidity:
      name: "Livingroom humidity"
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    pin: 5
    name: "PIR Sensor"
    device_class: motion